package mbkp

import (
	"os"
	"path/filepath"
	"testing"
)

// pxb84BackupMyCnf is the backup-my.cnf content Percona XtraBackup 8.4 wrote
// for a Percona Server 8.4 instance during a real backup run; note xtrabackup
// records the key as server_uuid (underscore), while auto.cnf uses
// server-uuid (hyphen).
const pxb84BackupMyCnf = `# This MySQL options file was generated by innobackupex.

# The MySQL server
[mysqld]
innodb_checksum_algorithm=crc32
innodb_log_checksums=1
innodb_data_file_path=ibdata1:12M:autoextend
innodb_log_file_size=50331648
innodb_page_size=16384
innodb_undo_directory=./
innodb_undo_tablespaces=2
server_id=0
innodb_log_checksums=ON
innodb_redo_log_encrypt=OFF
innodb_undo_log_encrypt=OFF
server_uuid=fe6c99d2-aa87-11f1-9f59-66ff9a0d7d9f
master_key_id=0
`

func writeBackupMyCnf(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, backupMyCnfFile), []byte(content), 0644); err != nil {
		t.Fatalf("failed to write test backup-my.cnf: %v", err)
	}
	return dir
}

func TestReadServerUUID(t *testing.T) {
	tests := []struct {
		name    string
		content string // empty means: no backup-my.cnf file at all
		want    string
	}{
		{"pxb 8.4 underscore key", pxb84BackupMyCnf, "fe6c99d2-aa87-11f1-9f59-66ff9a0d7d9f"},
		{"hyphen key", "[mysqld]\nserver-uuid=3e11fa47-71ca-11e1-9e33-c80aa9429562\n", "3e11fa47-71ca-11e1-9e33-c80aa9429562"},
		{"spaced and quoted value", "[mysqld]\n server-uuid = \"3e11fa47-71ca-11e1-9e33-c80aa9429562\" \n", "3e11fa47-71ca-11e1-9e33-c80aa9429562"},
		{"uppercase value", "server_uuid=3E11FA47-71CA-11E1-9E33-C80AA9429562\n", "3E11FA47-71CA-11E1-9E33-C80AA9429562"},
		{"no server-uuid entry", "[mysqld]\ninnodb_page_size=16384\n", ""},
		{"malformed value", "server_uuid=not-a-uuid\n", ""},
		{"prefixed key does not match", "server_uuidx=3e11fa47-71ca-11e1-9e33-c80aa9429562\n", ""},
		{"commented line does not match", "# server_uuid=3e11fa47-71ca-11e1-9e33-c80aa9429562\n", ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var dir string
			if tt.content == "" {
				dir = t.TempDir()
			} else {
				dir = writeBackupMyCnf(t, tt.content)
			}
			if got := readServerUUID(dir); got != tt.want {
				t.Errorf("readServerUUID() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestIsValidServerUUID(t *testing.T) {
	tests := []struct {
		input string
		want  bool
	}{
		{"fe6c99d2-aa87-11f1-9f59-66ff9a0d7d9f", true},
		{"3E11FA47-71CA-11E1-9E33-C80AA9429562", true},
		{"", false},
		{"not-a-uuid", false},
		{"3e11fa47-71ca-11e1-9e33-c80aa942956", false},   // 35 chars
		{"3e11fa47-71ca-11e1-9e33-c80aa94295622", false}, // 37 chars
		{"3e11fa47_71ca-11e1-9e33-c80aa9429562", false},  // wrong separator position
		{"3e11fa4g-71ca-11e1-9e33-c80aa9429562", false},  // non-hex digit
	}
	for _, tt := range tests {
		if got := isValidServerUUID(tt.input); got != tt.want {
			t.Errorf("isValidServerUUID(%q) = %v, want %v", tt.input, got, tt.want)
		}
	}
}

func TestWriteAutoCnf(t *testing.T) {
	dir := t.TempDir()
	uuid := "fe6c99d2-aa87-11f1-9f59-66ff9a0d7d9f"

	if err := writeAutoCnf(dir, uuid); err != nil {
		t.Fatalf("writeAutoCnf() error = %v", err)
	}

	path := filepath.Join(dir, autoCnfFile)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read written auto.cnf: %v", err)
	}
	want := "[auto]\nserver-uuid=" + uuid + "\n"
	if string(data) != want {
		t.Errorf("auto.cnf content = %q, want %q", string(data), want)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("failed to stat written auto.cnf: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0644 {
		t.Errorf("auto.cnf permissions = %o, want 644", perm)
	}

	// A second write must overwrite cleanly (e.g. restoring the same backup
	// into a re-created datadir).
	if err := writeAutoCnf(dir, uuid); err != nil {
		t.Fatalf("second writeAutoCnf() error = %v", err)
	}
}
