package mbkp

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// pxb84BackupMyCnf is the backup-my.cnf content Percona XtraBackup 8.4 wrote
// for a Percona Server 8.4 instance during a real backup run; note xtrabackup
// records the key as server_uuid (underscore), while auto.cnf uses
// server-uuid (hyphen).
const pxb84BackupMyCnf = `# This MySQL options file was generated by innobackupex.

# The MySQL server
[mysqld]
innodb_checksum_algorithm=crc32
innodb_log_checksums=1
innodb_data_file_path=ibdata1:12M:autoextend
innodb_log_file_size=50331648
innodb_page_size=16384
innodb_undo_directory=./
innodb_undo_tablespaces=2
server_id=0
innodb_log_checksums=ON
innodb_redo_log_encrypt=OFF
innodb_undo_log_encrypt=OFF
server_uuid=fe6c99d2-aa87-11f1-9f59-66ff9a0d7d9f
master_key_id=0
`

func writeBackupMyCnf(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, backupMyCnfFile), []byte(content), 0644); err != nil {
		t.Fatalf("failed to write test backup-my.cnf: %v", err)
	}
	return dir
}

func TestReadServerUUID(t *testing.T) {
	tests := []struct {
		name    string
		content string // empty means: no backup-my.cnf file at all
		want    string
	}{
		{"pxb 8.4 underscore key", pxb84BackupMyCnf, "fe6c99d2-aa87-11f1-9f59-66ff9a0d7d9f"},
		{"hyphen key", "[mysqld]\nserver-uuid=3e11fa47-71ca-11e1-9e33-c80aa9429562\n", "3e11fa47-71ca-11e1-9e33-c80aa9429562"},
		{"spaced and quoted value", "[mysqld]\n server-uuid = \"3e11fa47-71ca-11e1-9e33-c80aa9429562\" \n", "3e11fa47-71ca-11e1-9e33-c80aa9429562"},
		{"uppercase value", "server_uuid=3E11FA47-71CA-11E1-9E33-C80AA9429562\n", "3E11FA47-71CA-11E1-9E33-C80AA9429562"},
		{"no server-uuid entry", "[mysqld]\ninnodb_page_size=16384\n", ""},
		{"malformed value", "server_uuid=not-a-uuid\n", ""},
		{"prefixed key does not match", "server_uuidx=3e11fa47-71ca-11e1-9e33-c80aa9429562\n", ""},
		{"commented line does not match", "# server_uuid=3e11fa47-71ca-11e1-9e33-c80aa9429562\n", ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var dir string
			if tt.content == "" {
				dir = t.TempDir()
			} else {
				dir = writeBackupMyCnf(t, tt.content)
			}
			if got := readServerUUID(dir); got != tt.want {
				t.Errorf("readServerUUID() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestIsValidServerUUID(t *testing.T) {
	tests := []struct {
		input string
		want  bool
	}{
		{"fe6c99d2-aa87-11f1-9f59-66ff9a0d7d9f", true},
		{"3E11FA47-71CA-11E1-9E33-C80AA9429562", true},
		{"", false},
		{"not-a-uuid", false},
		{"3e11fa47-71ca-11e1-9e33-c80aa942956", false},   // 35 chars
		{"3e11fa47-71ca-11e1-9e33-c80aa94295622", false}, // 37 chars
		{"3e11fa47_71ca-11e1-9e33-c80aa9429562", false},  // wrong separator position
		{"3e11fa4g-71ca-11e1-9e33-c80aa9429562", false},  // non-hex digit
	}
	for _, tt := range tests {
		if got := isValidServerUUID(tt.input); got != tt.want {
			t.Errorf("isValidServerUUID(%q) = %v, want %v", tt.input, got, tt.want)
		}
	}
}

func TestWriteAutoCnf(t *testing.T) {
	dir := t.TempDir()
	uuid := "fe6c99d2-aa87-11f1-9f59-66ff9a0d7d9f"

	if err := writeAutoCnf(dir, uuid); err != nil {
		t.Fatalf("writeAutoCnf() error = %v", err)
	}

	path := filepath.Join(dir, autoCnfFile)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read written auto.cnf: %v", err)
	}
	want := "[auto]\nserver-uuid=" + uuid + "\n"
	if string(data) != want {
		t.Errorf("auto.cnf content = %q, want %q", string(data), want)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("failed to stat written auto.cnf: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0644 {
		t.Errorf("auto.cnf permissions = %o, want 644", perm)
	}

	// A second write must overwrite cleanly (e.g. restoring the same backup
	// into a re-created datadir).
	if err := writeAutoCnf(dir, uuid); err != nil {
		t.Fatalf("second writeAutoCnf() error = %v", err)
	}
}

func TestBackupIDValidation(t *testing.T) {
	validIDs := []string{
		"full_20260914_093000_482",
		"inc_20260914_093000_482",
		"full-123",
		"backup1",
		"TEST_BACKUP-01",
	}
	for _, id := range validIDs {
		if !isValidBackupID(id) {
			t.Errorf("isValidBackupID(%q) = false, want true", id)
		}
	}

	invalidIDs := []string{
		"",
		"../../etc",
		"backup/sub",
		"backup;rm",
		"id with spaces",
		"backup.tar.gz",
		"backup$var",
	}
	for _, id := range invalidIDs {
		if isValidBackupID(id) {
			t.Errorf("isValidBackupID(%q) = true, want false", id)
		}
	}

	cfg := &Config{BackupDir: t.TempDir()}
	if err := RestoreBackup(cfg, "../../bad", "/tmp/datadir", false, false); err == nil || !strings.Contains(err.Error(), "invalid backup ID") {
		t.Errorf("RestoreBackup with invalid ID expected error, got %v", err)
	}

	if _, err := PrepareChain(cfg, "../../bad"); err == nil || !strings.Contains(err.Error(), "invalid backup ID") {
		t.Errorf("PrepareChain with invalid ID expected error, got %v", err)
	}

	if err := RunIncrementalBackup(cfg, "../../bad"); err == nil || !strings.Contains(err.Error(), "invalid parent backup ID") {
		t.Errorf("RunIncrementalBackup with invalid parent ID expected error, got %v", err)
	}
}

func TestPrepareChainCleansUpOnFailure(t *testing.T) {
	tmpDir := t.TempDir()
	cfg := &Config{
		BackupDir: tmpDir,
		StreamBin: "false",
		BackupBin: "false",
	}

	// Add a backup entry in the database
	b := BackupMetadata{
		ID:        "full-test-cleanup",
		Type:      "full",
		Status:    "completed",
		StartTime: time.Now().Add(-10 * time.Minute),
		EndTime:   time.Now().Add(-5 * time.Minute),
		Path:      "corrupt.xbstream.gz",
	}
	if err := AddBackup(tmpDir, b); err != nil {
		t.Fatalf("AddBackup failed: %v", err)
	}
	// Create corrupt archive file
	if err := os.WriteFile(filepath.Join(tmpDir, b.Path), []byte("corrupted archive"), 0644); err != nil {
		t.Fatalf("failed to write dummy archive: %v", err)
	}

	prepareDir := filepath.Join(tmpDir, "prepare_"+b.ID)

	_, err := PrepareChain(cfg, b.ID)
	if err == nil {
		t.Fatal("expected PrepareChain to fail, but got nil")
	}

	// Verify prepareDir was cleaned up and does not exist
	if _, err := os.Stat(prepareDir); !os.IsNotExist(err) {
		t.Errorf("prepareDir %s still exists after failure, expected it to be cleaned up", prepareDir)
	}
}

func TestRestoreBackupDatadirFailFast(t *testing.T) {
	tmpDir := t.TempDir()
	cfg := &Config{
		BackupDir: tmpDir,
		StreamBin: "nonexistent-stream-bin",
		BackupBin: "nonexistent-backup-bin",
	}

	// Empty datadir parameter
	if err := RestoreBackup(cfg, "valid-id", "", false, false); err == nil || !strings.Contains(err.Error(), "datadir must be specified") {
		t.Errorf("RestoreBackup with empty datadir expected error, got %v", err)
	}

	// Non-empty datadir parameter
	dataDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dataDir, "somefile.txt"), []byte("data"), 0644); err != nil {
		t.Fatalf("failed to write file in datadir: %v", err)
	}

	// Should fail fast before even looking for backup tools or resolving backup
	err := RestoreBackup(cfg, "valid-id", dataDir, false, false)
	if err == nil || !strings.Contains(err.Error(), "is not empty") {
		t.Errorf("RestoreBackup with non-empty datadir expected error about not empty, got %v", err)
	}

	// Datadir pointing to a file instead of directory
	filePath := filepath.Join(tmpDir, "file_as_dir")
	if err := os.WriteFile(filePath, []byte("data"), 0644); err != nil {
		t.Fatalf("failed to write file: %v", err)
	}
	err = RestoreBackup(cfg, "valid-id", filePath, false, false)
	if err == nil || !strings.Contains(err.Error(), "is not a directory") {
		t.Errorf("RestoreBackup with file datadir expected 'not a directory' error, got %v", err)
	}
}
